url_letters = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890_-" #allowed characters in auto generated and custom urls. beware, as adding to this may lead to security vulnerabilities
domain = "url.lucasvl.nl" #domain to show for link output
url_length = 6 #length of randomly generated url
max_link_length = 500 #maximum length of link to be shortened
max_url_length = 64 #maximum length of a custom url
max_age = 24 #max age of a url before it deletes itself, in hours (decimal values OK)
default_age = 2 #default age value used if user does not specify
port = 8080 #port that the server runs on
title = "My URL Shortener" #title displayed on browser bar
